// <auto-generated />
namespace PCBookWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_zone_manager_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_zone_manager_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201803020950311_update_zone_manager_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
